# Generated by rust2rpm 21
%bcond_without check
%global debug_package %{nil}

%global crate tracing-subscriber

Name:           rust-%{crate}
Version:        0.3.9
Release:        %autorelease
Summary:        Utilities for implementing and composing `tracing` subscribers

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/tracing-subscriber
Source:         %{crates_source}
# Initial patched metadata
Patch0:         tracing-subscriber-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Utilities for implementing and composing `tracing` subscribers.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ansi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ansi-devel %{_description}

This package contains library source intended for building other packages which
use the "ansi" feature of the "%{crate}" crate.

%files       -n %{name}+ansi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ansi_term-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ansi_term-devel %{_description}

This package contains library source intended for building other packages which
use the "ansi_term" feature of the "%{crate}" crate.

%files       -n %{name}+ansi_term-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+env-filter-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+env-filter-devel %{_description}

This package contains library source intended for building other packages which
use the "env-filter" feature of the "%{crate}" crate.

%files       -n %{name}+env-filter-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fmt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fmt-devel %{_description}

This package contains library source intended for building other packages which
use the "fmt" feature of the "%{crate}" crate.

%files       -n %{name}+fmt-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+json-devel %{_description}

This package contains library source intended for building other packages which
use the "json" feature of the "%{crate}" crate.

%files       -n %{name}+json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+lazy_static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lazy_static-devel %{_description}

This package contains library source intended for building other packages which
use the "lazy_static" feature of the "%{crate}" crate.

%files       -n %{name}+lazy_static-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-time-devel %{_description}

This package contains library source intended for building other packages which
use the "local-time" feature of the "%{crate}" crate.

%files       -n %{name}+local-time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+matchers-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+matchers-devel %{_description}

This package contains library source intended for building other packages which
use the "matchers" feature of the "%{crate}" crate.

%files       -n %{name}+matchers-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+parking_lot-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parking_lot-devel %{_description}

This package contains library source intended for building other packages which
use the "parking_lot" feature of the "%{crate}" crate.

%files       -n %{name}+parking_lot-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+regex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-devel %{_description}

This package contains library source intended for building other packages which
use the "regex" feature of the "%{crate}" crate.

%files       -n %{name}+regex-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+registry-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+registry-devel %{_description}

This package contains library source intended for building other packages which
use the "registry" feature of the "%{crate}" crate.

%files       -n %{name}+registry-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_json-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_json" feature of the "%{crate}" crate.

%files       -n %{name}+serde_json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sharded-slab-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sharded-slab-devel %{_description}

This package contains library source intended for building other packages which
use the "sharded-slab" feature of the "%{crate}" crate.

%files       -n %{name}+sharded-slab-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+smallvec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+smallvec-devel %{_description}

This package contains library source intended for building other packages which
use the "smallvec" feature of the "%{crate}" crate.

%files       -n %{name}+smallvec-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+thread_local-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+thread_local-devel %{_description}

This package contains library source intended for building other packages which
use the "thread_local" feature of the "%{crate}" crate.

%files       -n %{name}+thread_local-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+time-devel %{_description}

This package contains library source intended for building other packages which
use the "time" feature of the "%{crate}" crate.

%files       -n %{name}+time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-log-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing-log" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-log-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-serde-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing-serde" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+valuable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+valuable-devel %{_description}

This package contains library source intended for building other packages which
use the "valuable" feature of the "%{crate}" crate.

%files       -n %{name}+valuable-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+valuable-serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+valuable-serde-devel %{_description}

This package contains library source intended for building other packages which
use the "valuable-serde" feature of the "%{crate}" crate.

%files       -n %{name}+valuable-serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+valuable_crate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+valuable_crate-devel %{_description}

This package contains library source intended for building other packages which
use the "valuable_crate" feature of the "%{crate}" crate.

%files       -n %{name}+valuable_crate-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
